# -*- coding: utf-8 -*-
"""Untitled31.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10YhL4umFe5WXRY6DLbRGOo3UpAieOXpj
"""

# -*- coding: utf-8 -*-
import pandas as pd
import numpy as np
import io
import os
import json
import joblib
import time
import requests
import asyncio
import traceback
from datetime import datetime, timedelta
from threading import Thread, Event
from typing import List

# --- Suppress InsecureRequestWarning ---
import urllib3
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

import tensorflow as tf
from PIL import Image
from fastapi import FastAPI, UploadFile, File, HTTPException, Form, WebSocket, WebSocketDisconnect
from fastapi.middleware.cors import CORSMiddleware


# ==============================================================================
# --- APPLICATION CONFIGURATION & GLOBAL STATE ---
# ==============================================================================
app = FastAPI(
    title="Poultry Analysis and Real-Time Monitoring API",
    description="API for poultry health analysis, image classification, and real-time environment monitoring."
)

# --- BigHerdsman API Credentials ---
USERNAME = "ADEL"
PASSWORD = "88888888"

# --- Gestion Robuste des Chemins de Fichiers ---
try:
    PROJECT_ROOT = os.path.dirname(os.path.abspath(__file__))
except NameError:
    PROJECT_ROOT = os.getcwd()

DATA_DIR = os.path.join(PROJECT_ROOT, "data")
os.makedirs(DATA_DIR, exist_ok=True)

# Définition de tous les chemins de modèles et de données
CSV_PATH = os.path.join(DATA_DIR, "historique_predictions.csv")
TFLITE_MODEL_PATH = "model.tflite"
SCALER_PKL_PATH = "scaler.pkl"
MODEL_PKL_PATH = "model.pkl"
POULTRY_TFLITE_PATH = "my_poultry_modelF17.tflite"
H5_MODEL_PATH = "mobilenetv2_1.00_224-Chicken Disease-97.52.h5"
REALTIME_MODEL_PATH = "model nv.pkl"
REALTIME_SCALER_PATH = "scaler nv.pkl"

# --- Global State for Real-Time Surveillance ---
surveillance_thread = None
stop_flag = Event()
main_loop = None


# ==============================================================================
# --- WEBSOCKET CONNECTION MANAGER ---
# ==============================================================================
class ConnectionManager:
    def __init__(self):
        self.active_connections: list[WebSocket] = []

    async def connect(self, websocket: WebSocket):
        await websocket.accept()
        self.active_connections.append(websocket)
        print(f"New client connected. Total clients: {len(self.active_connections)}")

    def disconnect(self, websocket: WebSocket):
        if websocket in self.active_connections:
            self.active_connections.remove(websocket)
        print(f"Client disconnected. Total clients: {len(self.active_connections)}")

    async def broadcast(self, message: str):
        for connection in self.active_connections[:]:
            try:
                await connection.send_text(message)
            except WebSocketDisconnect: self.disconnect(connection)
            except Exception as e:
                print(f"Error sending to a websocket client: {e}")
                self.disconnect(connection)

manager = ConnectionManager()


# ==============================================================================
# --- MODEL LOADING ---
# ==============================================================================
def load_model(path, model_type="joblib"):
    if not os.path.exists(path):
        print(f"⚠️ Warning: Model file not found at {path}")
        return None
    try:
        if model_type == "joblib": model = joblib.load(path)
        elif model_type == "tflite":
            interpreter = tf.lite.Interpreter(model_path=path)
            interpreter.allocate_tensors()
            return interpreter
        elif model_type == "h5": model = tf.keras.models.load_model(path)
        else: return None
        print(f"✅ {model_type.capitalize()} model loaded: {path}")
        return model
    except Exception as e:
        print(f"❌ Error loading {path}: {e}")
        return None

print("--- Loading All Models ---")
# Modèles pour la prédiction 'single' et 'csv'
model_pkl = load_model(MODEL_PKL_PATH, "joblib")
scaler_pkl = load_model(SCALER_PKL_PATH, "joblib")
interpreter = load_model(TFLITE_MODEL_PATH, "tflite")

# Modèles pour la surveillance temps réel
realtime_model = load_model(REALTIME_MODEL_PATH, "joblib")
realtime_scaler = load_model(REALTIME_SCALER_PATH, "joblib")

# Modèles pour l'analyse d'image
poultry_interpreter = load_model(POULTRY_TFLITE_PATH, "tflite")
h5_model = load_model(H5_MODEL_PATH, "h5")

# Extraction des détails d'input/output pour TFLite
input_details, output_details = (None, None)
poultry_input_details, poultry_output_details = (None, None)
if poultry_interpreter:
    poultry_input_details = poultry_interpreter.get_input_details()
    poultry_output_details = poultry_interpreter.get_output_details()
if interpreter:
    input_details = interpreter.get_input_details()
    output_details = interpreter.get_output_details()


# ==============================================================================
# --- FASTAPI APP INITIALIZATION & MIDDLEWARE ---
# ==============================================================================
app.add_middleware(CORSMiddleware, allow_origins=["*"], allow_credentials=True, allow_methods=["*"], allow_headers=["*"])

@app.on_event("startup")
async def startup_event():
    global main_loop
    main_loop = asyncio.get_running_loop()
    print("Application startup complete.")


# ==============================================================================
# --- HELPER FUNCTIONS ---
# ==============================================================================
def get_humidite_critique(age):
    table = { 1: 70, 2: 70, 3: 70, 4: 70, 5: 70, 6: 70, 7: 65, 8: 65, 9: 65, 10: 65, 11: 65, 12: 65, 13: 65, 14: 60, 15: 60, 16: 60, 17: 60, 18: 60, 19: 60, 20: 60, 21: 55, 22: 55, 23: 55, 24: 55, 25: 55, 26: 55, 27: 50, 28: 50, 29: 50, 30: 50, 31: 50, 32: 50, 33: 50, 34: 50, 35: 50, 36: 50, 37: 50, 38: 50, 39: 50, 40: 50, 41: 50, 42: 50, 43: 50, 44: 50, 45: 50, 46: 50, 47: 50, 48: 50 }
    return table.get(int(age), 50)

def get_token():
    try:
        resp = requests.post("https://iot1.bigherdsman.com/api/v2/account/login/", json={"username": USERNAME, "password": PASSWORD}, timeout=20, verify=False)
        resp.raise_for_status()
        return resp.json()["data"]["token"]
    except requests.RequestException as e:
        print(f"[{datetime.now()}] API Error (get_token): {e}")
        return None

def get_farm_code(headers):
    try:
        resp = requests.get("https://iot1.bigherdsman.com/api/v2/entity/farm", headers=headers, timeout=20, verify=False)
        resp.raise_for_status()
        return resp.json()["data"][0]["code"]
    except (requests.RequestException, IndexError, KeyError) as e:
        print(f"[{datetime.now()}] API Error (get_farm_code): {e}")
        return None

def fetch_farm_data(headers, farm_code):
    try:
        resp = requests.get(f"https://iot1.bigherdsman.com/api/v2/current/list/?code={farm_code}", headers=headers, timeout=20, verify=False)
        resp.raise_for_status()
        return resp.json().get("data")
    except requests.RequestException as e:
        print(f"[{datetime.now()}] API Error (fetch_farm_data): {e}")
        return None


# ==============================================================================
# --- REAL-TIME SURVEILLANCE LOGIC ---
# ==============================================================================
def fetch_and_predict_realtime():
    """Fetches data, predicts, saves, and broadcasts via WebSocket."""
    try:
        token = get_token()
        if not token:
            if main_loop: asyncio.run_coroutine_threadsafe(manager.broadcast(json.dumps({"error": "Failed to get API token."})), main_loop)
            return

        headers = {"Authorization": f"Token {token}"}
        farm_code = get_farm_code(headers)
        if not farm_code:
            if main_loop: asyncio.run_coroutine_threadsafe(manager.broadcast(json.dumps({"error": "Failed to get farm code."})), main_loop)
            return

        data = fetch_farm_data(headers, farm_code)
        if not data:
            print(f"[{datetime.now()}] No new data received from API.")
            return

        df = pd.DataFrame(data)
        df_flat = pd.json_normalize(df['data'])
        df = pd.concat([df[['ts']], df_flat], axis=1)
        df['datetime'] = pd.to_datetime(df['ts'].astype(int), unit='s')
        df = df.rename(columns={'age': 'Age', 'co2': 'CO2', 't_t': 'Req Temp', 't_cur': 'Temp', 'h_r': 'Humidity'})

        features_to_check = ['Age', 'CO2', 'Req Temp', 'Temp', 'Humidity']
        for col in features_to_check:
            df[col] = pd.to_numeric(df[col], errors='coerce')
        df.dropna(subset=features_to_check, inplace=True)

        if df.empty: return

        df['Humidite_Critique (%)'] = df['Age'].apply(get_humidite_critique)
        features = ['Age', 'CO2', 'Req Temp', 'Temp', 'Humidity', 'Humidite_Critique (%)']

        X = df[features]
        X_scaled = realtime_scaler.transform(X)
        y_proba = realtime_model.predict_proba(X_scaled)[:, 1]

        df['Status'] = np.where(y_proba >= 0.5, 'Abnormal', 'Normal')
        df['Proba_Abnormal_pct'] = (y_proba * 100).round(1)
        df['Proba_Normal_pct'] = ((1 - y_proba) * 100).round(1)
        print(f"[{datetime.now()}] Real-time prediction successful. Found {len(df)} records.")

        try:
            df_for_history = df[['datetime'] + features + ['Status', 'Proba_Normal_pct', 'Proba_Abnormal_pct']]
            header = not os.path.exists(CSV_PATH)
            df_for_history.to_csv(CSV_PATH, mode='a', header=header, index=False)
        except Exception as e:
            print(f"[{datetime.now()}] ⚠️ WARNING: Could not save to history file: {e}")

        df['datetime_str'] = df['datetime'].dt.strftime('%Y-%m-%d %H:%M:%S')
        cols_for_flutter = ['datetime_str', 'Temp', 'Humidity', 'CO2', 'Status', 'Proba_Normal_pct', 'Proba_Abnormal_pct']
        for _, row in df[cols_for_flutter].iterrows():
            if main_loop:
                asyncio.run_coroutine_threadsafe(manager.broadcast(row.to_json()), main_loop)

    except Exception as e:
        error_msg = f"Critical error in surveillance loop: {str(e)}"
        print(f"[{datetime.now()}] ❌ {error_msg}")
        if main_loop:
            asyncio.run_coroutine_threadsafe(manager.broadcast(json.dumps({"error": error_msg})), main_loop)

def surveillance_loop_runner():
    print(">>> Background surveillance loop is now ACTIVE.")
    while not stop_flag.is_set():
        fetch_and_predict_realtime()
        time.sleep(15)
    print(">>> Background surveillance loop has TERMINATED.")


# ==============================================================================
# --- API ENDPOINTS ---
# ==============================================================================

# --- Real-Time Monitoring Control ---
@app.post("/monitoring/start", tags=["Monitoring"], summary="Starts real-time data monitoring")
async def start_monitoring():
    global surveillance_thread
    if not all([realtime_model, realtime_scaler]):
         raise HTTPException(status_code=503, detail="Real-time model or scaler not loaded.")
    if surveillance_thread and surveillance_thread.is_alive():
        return {"status": "already_running"}
    stop_flag.clear()
    surveillance_thread = Thread(target=surveillance_loop_runner)
    surveillance_thread.start()
    return {"status": "started"}

@app.post("/monitoring/stop", tags=["Monitoring"], summary="Stops real-time data monitoring")
async def stop_monitoring():
    global surveillance_thread
    if not surveillance_thread or not surveillance_thread.is_alive():
        return {"status": "not_running"}
    stop_flag.set()
    surveillance_thread.join(timeout=5)
    surveillance_thread = None
    return {"status": "stopped"}

@app.get("/monitoring/status", tags=["Monitoring"], summary="Checks monitoring status")
async def get_monitoring_status():
    return {"status": "running" if surveillance_thread and surveillance_thread.is_alive() else "stopped"}

@app.get("/monitoring/history", tags=["Monitoring"], summary="Gets historical monitoring data")
async def get_monitoring_history(hours: int = 24):
    if not os.path.exists(CSV_PATH): return []
    try:
        hist_df = pd.read_csv(CSV_PATH)
        hist_df['datetime'] = pd.to_datetime(hist_df['datetime'])
        filtered_df = hist_df[hist_df['datetime'] >= datetime.now() - timedelta(hours=hours)]
        return filtered_df.where(pd.notnull(filtered_df), None).to_dict(orient='records')
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Error reading history file: {str(e)}")

# --- WebSocket Endpoint ---
@app.websocket("/ws/realtime")
async def websocket_endpoint(websocket: WebSocket):
    await manager.connect(websocket)
    try:
        while True: await websocket.receive_text()
    except WebSocketDisconnect: manager.disconnect(websocket)

# --- Endpoints for CSV and Single Prediction (Merged from original) ---
EXPECTED_COLUMNS = ['Age', 'CO2', 'Req Temp', 'Temp', 'Humidity', 'Vent Level', 'Daily Water', 'Totle Aday Feed', 'Fan Nums']
REQUIRED_COLUMNS = EXPECTED_COLUMNS + ['Humidite_Critique (%)']

@app.post("/predict", tags=["Prediction"], summary="Predict from CSV file")
async def predict_from_csv(file: UploadFile = File(...)):
    if not all([scaler_pkl, interpreter, input_details, output_details]):
        raise HTTPException(status_code=503, detail="CSV prediction model, scaler, or its details are not loaded.")

    try:
        content = await file.read()
        df = pd.read_csv(io.StringIO(content.decode('utf-8')))

        if not all(col in df.columns for col in EXPECTED_COLUMNS):
            missing_cols = [col for col in EXPECTED_COLUMNS if col not in df.columns]
            raise HTTPException(status_code=400, detail=f"CSV is missing columns: {', '.join(missing_cols)}")

        df['Humidite_Critique (%)'] = df['Age'].apply(get_humidite_critique)

        # Préparation des données pour le modèle
        scaled = scaler_pkl.transform(df[REQUIRED_COLUMNS])
        input_data = scaled.astype(input_details[0]['dtype'])

        # ✨ CORRECTION CRITIQUE : Redimensionner le tenseur d'entrée du modèle TFLite ✨
        interpreter.resize_tensor_input(input_details[0]['index'], input_data.shape)
        interpreter.allocate_tensors()

        # Prédiction
        interpreter.set_tensor(input_details[0]['index'], input_data)
        interpreter.invoke()
        output = interpreter.get_tensor(output_details[0]['index'])

        y_proba = output.flatten()
        df_result = df[['Age', 'Temp', 'Humidity']].copy()
        df_result['Status'] = np.where(y_proba >= 0.5, 'Abnormal', 'Normal')
        df_result['Proba_Abnormal (%)'] = (y_proba * 100).round(2)
        df_result['Proba_Normal (%)'] = ((1 - y_proba) * 100).round(2)

        return df_result.to_dict(orient='records')

    except Exception as e:
        print(f"❌ An error occurred in /predict: {str(e)}")
        traceback.print_exc()
        raise HTTPException(status_code=500, detail=f"Error during CSV prediction: {str(e)}")


@app.post("/predict_single", tags=["Prediction"], summary="Predict from single form data")
async def predict_single(
    age: int = Form(...), co2: float = Form(...), req_temp: float = Form(...),
    temp: float = Form(...), humidity: float = Form(...), vent_level: float = Form(...),
    daily_water: float = Form(...), feed: float = Form(...), fan_nums: int = Form(...)
):
    if not all([model_pkl, scaler_pkl]):
        raise HTTPException(status_code=503, detail="Single prediction model or scaler not loaded.")

    data = {'Age': age, 'CO2': co2, 'Req Temp': req_temp, 'Temp': temp, 'Humidity': humidity, 'Vent Level': vent_level, 'Daily Water': daily_water, 'Totle Aday Feed': feed, 'Fan Nums': fan_nums}
    df = pd.DataFrame([data])
    df['Humidite_Critique (%)'] = df['Age'].apply(get_humidite_critique)

    try:
        X_scaled = scaler_pkl.transform(df[REQUIRED_COLUMNS])
        y_pred = model_pkl.predict(X_scaled)
        y_proba = model_pkl.predict_proba(X_scaled)[:, 1]
        return {
            "Status": "Abnormal" if y_pred[0] == 1 else "Normal",
            "Proba_Abnormal (%)": round(y_proba[0] * 100, 2),
            "Proba_Normal (%)": round((1 - y_proba[0]) * 100, 2)
        }
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Error during single prediction: {str(e)}")


# --- Image Analysis Endpoints ---
def process_image(contents: bytes, size=(224, 224)):
    image = Image.open(io.BytesIO(contents)).convert("RGB").resize(size)
    img_array = np.array(image, dtype=np.float32) / 255.0
    return np.expand_dims(img_array, axis=0)

@app.post("/analyze_poultry_image", tags=["Image Analysis"], summary="Analyze poultry health from image")
async def analyze_poultry_image(file: UploadFile = File(...)):
    if not all([poultry_interpreter, poultry_input_details, poultry_output_details]):
        raise HTTPException(status_code=503, detail="Poultry image model or its details are not loaded.")
    try:
        img_array = process_image(await file.read())
        poultry_interpreter.set_tensor(poultry_input_details[0]['index'], img_array)
        poultry_interpreter.invoke()
        is_sick_prob = poultry_interpreter.get_tensor(poultry_output_details[0]['index'])[0][0]

        pred_class = "Sick" if is_sick_prob >= 0.5 else "Healthy"
        confidence = is_sick_prob if pred_class == "Sick" else 1 - is_sick_prob
        return {"status": pred_class, "confidence": round(confidence * 100, 2), "filename": file.filename}
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Error analyzing poultry image: {str(e)}")

@app.post("/analyze_dropping_image", tags=["Image Analysis"], summary="Analyze dropping health from image")
async def analyze_dropping_image(file: UploadFile = File(...)):
    if h5_model is None: raise HTTPException(status_code=503, detail="Dropping analysis model not loaded.")
    try:
        img_array = process_image(await file.read())
        is_sick_prob = h5_model.predict(img_array)[0][0]

        pred_class = "Sick" if is_sick_prob >= 0.5 else "Healthy"
        confidence = is_sick_prob if pred_class == "Sick" else 1 - is_sick_prob
        # Capitalize la première lettre pour la cohérence (Sick, Healthy)
        return {"status": pred_class.capitalize(), "confidence": round(confidence * 100, 2), "filename": file.filename}
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Error analyzing dropping image: {str(e)}")